### ISSUE TITLE
"Failed to set activity: Failed to subscribe to event"

### ISSUE THREAD

**Issue by kunamech** [JakeStanger/mpd-discord-rpc#24]
```
Entering idle mode
Exiting idle mode
Failed to set activity: Failed to subscribe to event
```
I've tried both cargo and AUR package using defaults. I'm using the regular `discord` package of Arch Linux.

**Comment by JakeStanger** [comment]
Hey, thanks for reporting, I've not seen this one before. Has the program ever worked for you before?

From some digging, I can see that the error comes from the discord RPC crate trying to make the connection to Discord.

One thing to check is if other rich presence-setting programs work for you (any game that supports it or script you find online or whatever). 

Also it might be worth checking the option to display your status is on, in case Discord just doesn't startup the RPC server if it's off:
![image](https://user-images.githubusercontent.com/5057870/171128271-66ae959e-e56f-4061-8b4f-5daeae31b998.png)

**Comment by AsianKoala** [comment]
I noticed this same problem earlier today, using the AUR package.

Other applications are successfully able to control my activity status, such as Spotify and osu!.

![image](https://user-images.githubusercontent.com/45741682/188775319-f3e24423-9172-4722-b9ec-2fc9fbc998f0.png)

**Comment by JakeStanger** [comment]
Odd... same question for you - was it working for you previously? Also what discord package are you using?

**Comment by AsianKoala** [comment]
No, this was the first time I have tried running it. I'm currently using the official [`discord`](https://archlinux.org/packages/community/x86_64/discord/) package off the AUR.

**Comment by JakeStanger** [comment]
Okay so I guess the most obvious route would be environment, if the same code is running & connecting to the same client fine for others. I know Arch works fine because I'm running it on that.

Are you using anything non-standard/security enhanced, like a hardened kernel or SELinux or a different init system or anything like that? What DE/WM/Compositor & Wayland or Xorg?

**Comment by AsianKoala** [comment]
Well, oddly enough the issue just resolved itself haha. I tried to reproduce this on my laptop, but that ended up in vain. Not really sure what fixed it as I haven't updated my system since then, but I guess all's well that ends well.

For what it's worth, I was using bspwm and xorg on both my desktop and laptop.

**Comment by JakeStanger** [comment]
Interesting, glad it's resolved at least. Thanks for the extra details.

**Comment by sivaplaysmC** [comment]
@JakeStanger  this issue arises when playing a non mp3 file , like a .webm file 

while playing other files like mp3s , there seemes to be no  problems

plus a huge :+1:  for your effort into this very useful application and I'm glad i am able to help the development 
of a very useful application :smiley: :smiley: :smiley: !

**Comment by JakeStanger** [comment]
Hm, that's interesting. I wonder if that's because it doesn't have the standard song metadata so one or more of the required fields end up blank. It sounds like I should be able to resolve this by just sticking "N/A" or "unknown" in place of the empty tags.
