### ISSUE TITLE
rich presence shows "unknown"

### ISSUE THREAD

**Issue by Latrolage** [JakeStanger/mpd-discord-rpc#34]
![image](https://user-images.githubusercontent.com/67372293/216809773-2405a61d-ec04-4507-bb4b-9a12b0ceb7f8.png)
Is this normal? There is no other stdout info 
```
❯ ./mpd-discord-rpc
Entering idle mode
Exiting idle mode
```

Also the AUR package doesn't seem to build properly.
```
Starting build()...
    Updating git repository `https://github.com/JakeStanger/discord-rpc-client.rs`
    Updating crates.io index
error: the lock file /home/user/.cache/paru/clone/mpd-discord-rpc/src/mpd-discord-rpc/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

**Comment by JakeStanger** [comment]
The program will fall back to "unknown" if a tag is missing - can you check if your music is tagged properly? If it is, what type of file is it, where is it sourced, and is MPD able to see the tags?

Regarding the AUR package, can you try removing your local cache and doing a clean build please?

**Comment by Kranzes** [comment]
This will fix the build failure https://github.com/JakeStanger/discord-rpc-client.rs/pull/1

**Comment by JakeStanger** [comment]
Cheers, didn't spot that PR. Lockfile & AUR package updated so should be working now.

**Comment by Kranzes** [comment]
> Cheers, didn't spot that PR. Lockfile & AUR package updated so should be working now.

Can you tag a release?

**Comment by JakeStanger** [comment]
Done

**Comment by Latrolage** [comment]
> The program will fall back to "unknown" if a tag is missing - can you check if your music is tagged properly? If it is, what type of file is it, where is it sourced, and is MPD able to see the tags?

Ah yeah looks like tagging was the issue. I ended up retagging my library with musicbrainz picard, I'm just curious what do you guys use for it? And if the song isn't on musicbrainz is it possible to fallback to using metadata in the file instead of just "unknown"

**Comment by JakeStanger** [comment]
> I'm just curious what do you guys use for it?

I use a mix of MusicBrainz Picard and PuddleTag. Picard is great for getting the bulk of the metadata, including the MUSICBRAINZ tags that things can hook into, and album art. PuddleTag offers a spreadsheet like editor which is great for bulk-editing and quick changes to stuff Picard can't do (or does badly).

> is it possible to fallback to using metadata in the file 

MPD's database is populated using the file metadata, which it automatically keeps up to date (unless you explicitly turn auto updates off). That means it'd be reading the same data, but doing it from disk instead of MPD's DB, so it still wouldn't exist.
